# Generated by Django 4.2.2 on 2023-06-10 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helloworldapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='option',
            field=models.TextField(null=True),
        ),
    ]
